### ISSUE TITLE
Allow customization of the Slack request notifier payload

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#18]
Currently the payload is static and provided verbatim to the notifier container, we should allow it to be configured. The Slack notifier container can receive any payload, it's simply a question of allowing this in the UI, and/or referring people to the Slack UI tool for testing messages, whilst also documenting what variables we export to the environment.

**Comment by DocEmmetBrown** [comment]
Don't know if it's really related, if needed I'll open a separate request: 
It would be a great improvement to have the project name in the slack message, so if having only one channel with all the projects we could know for sure which project has automatically deployed ;)
