### ISSUE TITLE
Implement "inheritance" between environments

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#19]
We recently introduced the "Default" environment, however there is no inheritance.

Inheritance from "Default" down to individual environments isn't implemented, and I'm personally not sure that it should be. I'd be glad to have some community input. I think a little repetition is better than more indirection, but I'm not the only stakeholder.

**Comment by DocEmmetBrown** [comment]
Totally agree with inheritance ;) 
From what I see, we'd 'source' the Default env, and then the current individual env. So we've got an entry point to set global variables for the whole project . Less repetitions, less chance of mistake ;)
