### ISSUE TITLE
Transpile coffee script to JavaScript

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#26]
We're really not fond of Coffee Script anymore. In 2015 when we started the Harrow project it still made sense, now - not so much. 

We need to look seriously at webpack and the module system and start taking the FE performance in terms of size, build tooling, etc a bit more seriously.

**Comment by kylewelsby** [comment]
I agree.  It was good in the early days, now having another dependency to compile code brings it's problems from what i can understand from the last time i touched the code. 

I will have a skim thru this, and push a PR if I'm able to get a working build.
