### ISSUE TITLE
Problem with basename after renamed repository in setup script leading to junk output at end of log

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#29]
The file `fsbuilder/rootfs/templates/setup.sh` should have some fixes to the `basename` usage, to ensure that basename responds without an error.

In a couple of cases of renamed repositories for a particular customer something appears to have gone wrong, with weird errors dumped at the end of the script run relating to basename problems.

**Comment by leehambley** [comment]
@DocEmmetBrown do you remember which one of your operations was causing this issue, if you can provide me the UUID I can probably ship a fix really quickly now.

**Comment by DocEmmetBrown** [comment]
Actually every task cloning our private repo
