### ISSUE TITLE
Occasional failure to connect to docker daemon early in script.

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#34]
Used to be very very infrequent, some users report it happening in 5-10% of builds which is unacceptable.

A workaround to wait for the Docker daemon to come up might be:

```
until docker ps
do
  echo "waiting for Docker to come-up"
  sleep 1
done
```

/cc @duizendnegen

**Comment by duizendnegen** [comment]
Thanks for the work-around, I'll try that out :+1:

**Comment by duizendnegen** [comment]
After `sleep`ing for a total of 45 minutes the Docker daemon still hasn't come up. So the work-around doesn't work :(

**Comment by leehambley** [comment]
> After sleeping for a total of 45 minutes the Docker daemon still hasn't come up.

Thanks, I'll investigate and keep you posted.

**Comment by leehambley** [comment]
I suspect I've found the reason:

- https://github.com/lxc/lxd/issues/2252

```
root@harrow-lxd-04 ~ # lxc launch harrow-baseimage check-docker-daemon-start-cmd
Creating check-docker-daemon-start-cmd
Starting check-docker-daemon-start-cmd
root@harrow-lxd-04 ~ # lxc exec check-docker-daemon-start-cmd -- sudo -u ubuntu /bin/bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

bash: /root/.bashrc: Permission denied
ubuntu@harrow-baseimage:~$ systemctl status docker
Failed to connect to bus: No such file or directory
ubuntu@harrow-baseimage:~$ systemctl show --property ActiveState docker
Failed to connect to bus: No such file or directory
ubuntu@harrow-baseimage:~$ sudo systemctl show --property ActiveState docker
ActiveState=inactive
ubuntu@harrow-baseimage:~$ sudo systemctl start docker
A dependency job for docker.service failed. See 'journalctl -xe' for details.
ubuntu@harrow-baseimage:~$ sudo systemctl start docker
Failed to allocate directory watch: Too many open files
A dependency job for docker.service failed. See 'journalctl -xe' for details.
```

**Comment by leehambley** [comment]
@duizendnegen Please can you let me know if your problem is solved?

**Comment by leehambley** [comment]
Confirmed it takes a little time for Docker to come up in some cases:

```
# export i=0
# lxc launch harrow-baseimage "docker-test-$i"
Creating docker-test-0
Starting docker-test-0
# lxc exec "docker-test-$i" -- sudo systemctl is-active docker
inactive
# lxc exec "docker-test-$i" -- sudo systemctl is-active docker
inactive
# lxc exec "docker-test-$i" -- sudo systemctl is-active docker
activating
# lxc exec "docker-test-$i" -- sudo systemctl is-active docker
active
# lxc delete --force "docker-test-$i"
```

Putting that into some context, with a 5 second timeout the results of the following mini test script are:

```
results=$(
for i in $(seq 10); do
  (>&2 echo -n ".")
  lxc launch harrow-baseimage "docker-test-$i"
  sleep 5
  lxc exec "docker-test-$i" -- sudo systemctl is-active docker
  lxc delete --force "docker-test-$i"
done
)
```

```
# echo "$results" | grep -vF "docker-test"
inactive
inactive
activating
activating
activating
inactive
inactive
inactive
inactive
activating
```

I read that as saying that after `5s` we can't be 100% sure that Docker is up. However we know for example that in most cases it takes at least 5 seconds to upload the user script payload and clone repositories, etc. Realistically you shouldn't be waiting *any* time at all for it to come up.

I'm running a larger scale test now, I'll update this with a follow-up comment shortly. 

*Note:* Without the referenced commit the results were *much* worse.

**Comment by duizendnegen** [comment]
Docker now comes up in all instances, this problem is solved from our side.

**Comment by leehambley** [comment]
Results from a larger scale test with a 10sec waiting time:

```
echo "$results" | grep -v docker-test | sort |  uniq -c
     40 activating
    375 active
     56 inactive
```

Docker boot time is still a bit too high, but if your problem is solved we can address that at a later time again when it becomes problematic again.

**Comment by duizendnegen** [comment]
From our side we're also :+1: to do a `sleep 30` at the start of the script, so...
