### ISSUE TITLE
Have a glimpse on the main metrics of the whole system 

### ISSUE THREAD

**Issue by DocEmmetBrown** [harrowio/harrow#35]
On very rare occasions, a "bad neighbour" in the worker's queue makes the system less responsive. 
It would be very helpful to have access to basic metrics to see if everything is normal or if the queue is behaving wrong. 
I was thinking of a light version of this kind of dashboard : http://monitor.gitlab.net/dashboard/db/ci ? 

Thanx

**Comment by leehambley** [comment]
Excellent idea. I'll take it onboard, I'm working on the logging and metrics systems for the next ~10 days anyway!
