### ISSUE TITLE
Possible 418 (Teapot) condition on invalid schedule

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#45]
A user-reported issue causing a 418 HTTP response was found because it was possible to create a `domain.Schedule` with both a `timespec` and a `cronspec` field populated.

Both the cronspec and timespec were unparsable:

```
cronspec         | 20 20 20 20 20
timespec         | /20 * * * *
```

This `cronspec` was invalid because `20` in the 4th field is invalid (month):
  
 - https://crontab.guru/#20_20_20_20_20

The `timespec` is invalid because it doesn't accept cronspecs:

 - https://www.apt-browse.org/browse/ubuntu/precise/main/i386/at/3.1.13-1ubuntu1/file/usr/share/doc/at/timespec

Probably we should have more validation up-front to prevent this case, however it's only the 2nd case ever of a 418 resulting from a bad timespec in 2 years of running Harrow, so possibly we're already validating this, but we miss some edge cases?

**Comment by DocEmmetBrown** [comment]
Can be merged with  #33  I guess ;)
