### ISSUE TITLE
Send email to project members on operation timeout

### ISSUE THREAD

**Issue by leehambley** [harrowio/harrow#46]
Timeouts should be an exceptional condition, following recent improvements they should be now.

Please +1 this comment if you're interested in this feature.

**Comment by kylewelsby** [comment]
:+1:  Yes,  if a operation takes longer than X to perform.  It's likely failed and thus needs attention.

**Comment by DocEmmetBrown** [comment]
Why not a "notification" rather than an "email" so it can be a slack , or maybe a webhook, or something else in the future ? but, yeah 👍
